# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-09-22 16:47:41
"""
import arcpy

def r5prep():  # r5prep

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    tract_points_raw_shp = "./temp_data/tract_points_raw.shp"
    main_lines = "./input_data/geofabrik_ohio-latest.gpkg/main.lines"
    points_raw_shp = "./temp_data/points_raw.shp"

    # Process: Copy Features (Copy Features) (management)
    tract_points_shp_2_ = "./temp_data/tract_points.shp"
    arcpy.management.CopyFeatures(in_features=tract_points_raw_shp, out_feature_class=tract_points_shp_2_, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

    # Process: Add Spatial Index (3) (Add Spatial Index) (management)
    Updated_Input_Features_3_ = arcpy.management.AddSpatialIndex(in_features=tract_points_shp_2_, spatial_grid_1=0, spatial_grid_2=0, spatial_grid_3=0)[0]

    # Process: Add Spatial Index (Add Spatial Index) (management)
    Updated_Input_Features = arcpy.management.AddSpatialIndex(in_features=main_lines, spatial_grid_1=0, spatial_grid_2=0, spatial_grid_3=0)[0]

    # Process: Snap (Snap) (edit)
    if Updated_Input_Features and Updated_Input_Features_3_:
        tract_points_shp_3_ = arcpy.edit.Snap(in_features=tract_points_shp_2_, snap_environment=[[main_lines, "VERTEX", "10 Miles"]])[0]

    # Process: Copy Features (2) (Copy Features) (management)
    points_shp_1_ = "./temp_data/points.shp"
    arcpy.management.CopyFeatures(in_features=points_raw_shp, out_feature_class=points_shp_1_, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

    # Process: Add Spatial Index (2) (Add Spatial Index) (management)
    Updated_Input_Features_2_ = arcpy.management.AddSpatialIndex(in_features=points_shp_1_, spatial_grid_1=0, spatial_grid_2=0, spatial_grid_3=0)[0]

    # Process: Snap (2) (Snap) (edit)
    if Updated_Input_Features and Updated_Input_Features_2_:
        points_shp_2_ = arcpy.edit.Snap(in_features=points_shp_1_, snap_environment=[[main_lines, "VERTEX", "1 Miles"]])[0]

if __name__ == '__main__':
    r5prep()
